name: env-secret-workflow.yml
on:
  push:
    branches:
      - main
      - master
jobs:
  build:
    environment: staging
    env:
      SUPER_SECRET: ${{ secrets.SUPER_SECRET }}
    runs-on: ubuntu-20.04
    steps:
      - name: first-step
        run: |
          echo "running first step"
          echo "my super secret is:  $SUPER_SECRET"
